### ISSUE TITLE
New words for apertium-dan

### ISSUE THREAD

**Issue by mortenivar** [apertium/apertium-dan#1]
I have created a list of words which all end in the letter 't' and which are not currently included in apertium-dan. I have marked up the list so it conforms to the format in apertium-dan.dan.dix. This is then a "feature request" of sorts which I submit in the hope that someone will include this list in apertium-dan.
[words-that-end-in-t.txt](https://github.com/apertium/apertium-dan/files/6489607/words-that-end-in-t.txt)

**Comment by mr-martian** [comment]
@mortenivar I would recommend adding these as a pull request.

**Comment by mortenivar** [comment]
Thanks Daniel. I am, however, not at all familiar with github.
It seems that in order to place a pull request, you need to
have pushed something first. But I haven't pushed anything.

Thanks,
Morten

**Comment by mr-martian** [comment]
When looking at the top-right corner part of the screen on the apertium-dan github page, there is a button that says "fork". Click that. You will then have a version of apertium-dan that you can edit.

Then make a copy of the `apertium-dan.dan.dix` that has the new words. The file is too big for the github interface, so go to the dictionary file and click the trash icon. Then go to the main screen and use the "add file" menu to upload your version of the dictionary and then after that there should be a button that says "open a pull request" or something like that.

(there are better ways to use git, but this will do for a start)

**Comment by mortenivar** [comment]
Thanks a lot for the guidance. I believe I have made a correct pull request, now.

**Comment by mr-martian** [comment]
It looks on my end like you removed
`<e lm="Norsk Manuellterapeutforening">	<i>Norsk<b/>Manuellterapeutforening</i><par n="Wikipedia__np"/></e>`
and added
```
<e lm="Sykehuspartner">	<i>Sykehuspartner</i><par n="Wikipedia__np"/></e>
<e lm="Sykehuspartner HF">	<i>Sykehuspartner<b/>HF</i><par n="Wikipedia__np"/></e>
<e lm="Sykehusinnkjøp">	<i>Sykehusinnkjøp</i><par n="Wikipedia__np"/></e>
<e lm="Sykehusinnkjøp HF">	<i>Sykehusinnkjøp<b/>HF</i><par n="Wikipedia__np"/></e>
```
which makes me think you may have uploaded the wrong file

**Comment by mortenivar** [comment]
Impressive how quickly you spotted that! I have uploaded the right file now. How do I see my pull requests? When I click on "Pull requests" in the top menu, it just shows "0 open". Sorry but I am new to this.

**Comment by mr-martian** [comment]
that looks correct now

when you go to https://github.com/mortenivar/apertium-dan do you see a green button that says "compare and pull request" ?

**Comment by mortenivar** [comment]
Nope. The only green buttons are "Code" and "Add a README".

**Comment by mr-martian** [comment]
The interface seems to have changed since the last time I opened a pull request. See https://github.com/apertium/apertium-dan/pull/2

If you make any more changes to your fork, they will get included in the pull request automatically.

**Comment by mortenivar** [comment]
But ...it is mentioned right on the top of the file list! Everything seems to be OK. Thanks for your quick and kind guidance.

**Comment by mr-martian** [comment]
you're welcome, and thanks for contributing!
